quotes_e10 = [
    '"It just kind of goes fwoomp" ~ Katherine',
    '"Where are your fingers?"',
    "It's not a story Dean Kamen would tell you",
    "*distant sea shanties*",
    "I feel very strongly that this is the wrong dad",
    "no u",
    "she thinks my tractors sexy",
    "Or in Seth wording... Ye",
    '"I\'ll be there a little late" ~ Ethan Brown, 2018',
    "technically yes, but no",
    "Remember if you can’t find love this valentines, it’s perfectly ok to blame programming",
    "Remember if you can’t find love this valentines, it’s perfectly ok to blame mechanical",
    '"cease" ~ Aryn',
    "this is wrong, I know this is wrong, but it works for no reason I understand",
    "Jankineered to perfection",
    "it worked in the cad",
    "You’ve done half a job but you’ve got a full smile",
    "Three smart freshman in calculus",
    "I think I broke the door",
    "I think we broke the window",
    "But you said speak the dark words, what if there were actually dark words?",
    "Apparently 135, the quadrangles, got RCA and qualified for Houston",
    "*screeching intensifies*",
    '"Yal\'l*" ~ jaxon8or (seen on IndianaFIRST)',
    '"Um, yes. Havent you seen space? I mean its so clearly filled with so much water" ~ Spencer',
    'By saying the word "kentucky", you have violated one of the laws of physics, and therefore do not exist ~ Tony',
    "`༼ つ ◕_ ◕ ༽つ GIVE BALANCE ༼ つ ◕_ ◕ ༽つ`",
    "*snap*",
    "the 40 monies are with the Crane discount. If you are on your own it is more like 50 monies. ~ Kvale",
    '"You are the dumbest smartest people I\'ve met" ~ Lander',
    '"Does screaming at my computer count as work?" "Yes, and it works for programming too."',
    "You're always a freshman in my heart",
    "No one knows everything, don't be afraid to ask a dumb question.",
    "Never miss a chance to tell someone you care about that you love them. You never know when you will be throat-kicked by a kung fu midget and lose the ability to speak.",
    "No hablo español",
    "Hi!",
    "why would you do that",
    "I'm treated like a god. Nobody pays any attention to my existence until they want something.",
    '"The roborio is squeaking Chris. Help" ~ Seth',
    "wanna see some python black magic? no? too bad",
    '"I tried to avoid going back to south for stuff tomorrow by packing *literally the entire Allen key drawer* but we still need to go back" ~ Seth',
    '"So here\'s the plan" "Lemme just go ahead and say no"',
    "were [sic] redesigning the robot. Don’t worry about it",
    "CAD stands for Cardboard Aided Design/Drafting",
    "Popcorn is a cheap, biodegradable way to actuate a robot (once)",
    "I love science",
    "Yep. We redid #info again. At 11:30 at night. Real competent administration here",
    "Hey you guys should probably make sure your homework is done for tommorow",
    "Whilst the safety of each safe is implied by its object class (whether Safe or not Safe), the practical safety of each safe is outlined below.",
    "Sriracha isn't a sauce it's a drink",
    "Installing Linux on a Dead Badger: User's Notes",
    "I'll try to be as dumb as possible",
    "its like water but land instead of wat",
    "can we put a mustache on Thotticus",
    "Hail HYDRA!",
    '"Yeah you can go ahead and stop now" ~ Lander, on suspended tank videos',
    "gotta love it when your king dies from hitting his head on a doorframe when he's visiting his birthplace",
    '"Unused CPU is wasted CPU" ~ Caleb',
    "DON'T UWU - $350 PENALTY",
    "This quote intentionally left blank",
    "If your neighborhoods lights don’t dim when your computer turns on it needs more sauce",
    '"can you say hi to [redacted] for me please?" "Of course! Will sky-writing do?"',
    "🌽",
    '"Any ideas on where to look?" "Ummmm" "Wonderful"',
    "I haven't seen any ears round here since the great ear removal of 2004",
    '"The King of France complains that I have twice decieved him. He lies, the fool; I have decieved him ten times and more." ~ Ferdinand the Catholic',
    "I just ran my hands through my hair and metal shavings fell out",
    "[ C O R N J O K E ]",
    "NEW! Corn on the Orb (it's round now)!",
    "you gotta score the boulders into the boiler then place the power cubes on the landfill",
    '"motors are powered by magic smoke, when they break it comes out and they stop working" ~ Seth',
    '"hey wheres [sic] state next year" "indiana?"',
    "we can only transmit so much ☭ at once you know",
    "carbon",
    "That's a horrible idea. Where's the angle grinder?",
    "Why is college math hard?",
    "I do not condone what I am about to do. Don't ever do it. Now let me start.",
    "It's not a bug, it's not a feature, it's an easter egg.",
    "СОГИ FОГ ТЋЁ СОГИ GOД",
    "quiet ree",
    '"I won\'t be there tonight" ~ Pretty much everyone, at some point',
    "wack",
    "double wack",
    '"The cheapest, fastest, and most reliable components are those that aren\'t there." ~ Gordon Bell',
    '"Just because the standard provides a cliff in front of you, you are not necessarily required to jump off it." ~ Norman Diamond',
    '"but\nthat\'s not an answer" "it\'s an answer, but not a reason"',
    "Hey, you.\nYou're finally awake.",
    "Apply garlic to a freshly opened cut or burn to immediately intensify the pain",
    '"i🖤anime" ~ Elon Musk',
    '"Is the pipeline literally running from your laptop?" "Don\'t be silly, my laptop disconnects far too often to host a service we rely on. It\'s running on my phone."',
    '"In most organizations HTTP traffic crosses firewalls fairly easily. Modern coffee pots do not use fire." ~ RFC 2324',
    "this problem requires a professional",
    "Like it was working then it wasn't",
    "Home movie makers were the original vloggers",
    "the guy next to me was playing despacito on a Bluetooth speaker",
    "we're having a slight mis-problem here",
    "it's not on fire or clowing red yet we're fine",
    '"the targeted ads figured out i was dead so now i only get ads for things dead people might like" ~ bill wurtz',
    "Add some quotes",
    "This gearbox has a 1024 million to one ratio and takes 47 days to complete a rotation.",
    "The easter bunny told me that Christmas isn't real",
    "You're all adults, you should know how HTTP status codes work.",
    "There are, like, three decent Christmas movies, and two of them are Die Hard.",
    "The devils [sic] beep beep lettuce",
    "Mr. Cruz, are you or have you ever been a fan of White Castle?",
    "one, a million, same thing",
    "It's nice and lukewarm, and by lukewarm I mean hot",
    "You are bad, in this case anyway",
    "Sure, we can machine that. *shakes head no*",
    "That's a code of conduct violation you know",
    '"failure comes in a pill. talk to your doctor about the failure pill. side effects may include success" ~ bill wurtz',
    '"if you are a pirate with no treasure, check the mirror, you might be the treasure" ~ bill wurtz',
    '"when watching comedy, always check what brow it is" ~ bill wurtz',
    "per my last email",
    "NO DEPLOY FRIDAYS",
    "I'm taking away your battery until you demonstrate that you’re being safe",
    "ｉｔ'ｓ ａｌｌ ｉｎ ｙｏｕｒ ｈｅａｄ",
]

quotes_unsafe = [
    "U N S A F E",
]
